### ISSUE TITLE
How to use event to reset the FancyScrollView

### ISSUE THREAD

**Issue by Liang2527** [setchi/FancyScrollView#56]
Hi, I very like the FancyScrollView
But I am facing some issues with resetting the scroller and its content.
For example, I want the Scroller and its contents to be reset whenever I press a button or hit something. By default, if I destroy the object inside the content, Unity will flag an error saying FancyScrollView is looking for objects that have been destroyed and stop the play. 
If I replace the object inside the content, the position of the viewport will not change. 

Is that any efficient way to reset the FancyScrollView? 
Thanks,

**Comment by setchi** [comment]
@Liang2527 
Sorry for my late reply.

Do not destroy cells directly as they are managed by FancyScrollView.
Basically, it updates the data rather than deleting the cell itself.
https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Examples/Sources/02_FocusOn/ScrollView.cs#L48

If you really need to destroy the cell, instead of deleting the cell directly, prepare your own container inside the cell and delete it.

The scroll position can be updated with scroller.ScrollTo();
https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Examples/Sources/02_FocusOn/ScrollView.cs#L75

**Comment by Liang2527** [comment]
> @Liang2527
> Sorry for my late reply.
> 
> Do not destroy cells directly as they are managed by FancyScrollView.
> Basically, it updates the data rather than deleting the cell itself.
> https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Examples/Sources/02_FocusOn/ScrollView.cs#L48
> 
> If you really need to destroy the cell, instead of deleting the cell directly, prepare your own container inside the cell and delete it.
> 
> The scroll position can be updated with scroller.ScrollTo();
> https://github.com/setchi/FancyScrollView/blob/master/Assets/FancyScrollView/Examples/Sources/02_FocusOn/ScrollView.cs#L75

Thanks
